language: ruby
sudo: false
before_install:
  - bundle config mirror.https://gems.ruby-china.org https://rubygems.org
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
